# Dockerfile.ui
FROM python:3.10-slim

WORKDIR /ui

COPY requirements.txt .
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY ui ./ui

CMD ["streamlit", "run", "ui/app.py", "--server.port=8501", "--server.address=0.0.0.0"]